<template>
    <TablerEnum
        :label='label'
        :options='Array.from(timezones)'
        :description='description'
        :autofocus='autofocus'
        :disabled='disabled'
        :required='required'
        :default='inverse.has(modelValue) ? inverse.get(modelValue) : "No TimeZone"'
        @change='$emit("update:modelValue", map.get($event.target.value).tzCode)'
    />
</template>

<script>
import TablerEnum from './Enum.vue'

const tzs = [
    { label:"Pacific/Midway (GMT-11:00)", "tzCode":"Pacific/Midway", },
    { label:"Pacific/Niue (GMT-11:00)", "tzCode":"Pacific/Niue", },
    { label:"Pacific/Pago_Pago (GMT-11:00)", "tzCode":"Pacific/Pago_Pago", },
    { label:"America/Adak (GMT-10:00)", "tzCode":"America/Adak", },
    { label:"Pacific/Honolulu (GMT-10:00)", "tzCode":"Pacific/Honolulu", },
    { label:"Pacific/Rarotonga (GMT-10:00)", "tzCode":"Pacific/Rarotonga", },
    { label:"Pacific/Tahiti (GMT-10:00)", "tzCode":"Pacific/Tahiti", },
    { label:"Pacific/Marquesas (GMT-09:30)", "tzCode":"Pacific/Marquesas", },
    { label:"America/Anchorage (GMT-09:00)", "tzCode":"America/Anchorage", },
    { label:"America/Juneau (GMT-09:00)", "tzCode":"America/Juneau", },
    { label:"America/Metlakatla (GMT-09:00)", "tzCode":"America/Metlakatla", },
    { label:"America/Nome (GMT-09:00)", "tzCode":"America/Nome", },
    { label:"America/Sitka (GMT-09:00)", "tzCode":"America/Sitka", },
    { label:"America/Yakutat (GMT-09:00)", "tzCode":"America/Yakutat", },
    { label:"Pacific/Gambier (GMT-09:00)", "tzCode":"Pacific/Gambier", },
    { label:"America/Los_Angeles (GMT-08:00)", "tzCode":"America/Los_Angeles", },
    { label:"America/Tijuana (GMT-08:00)", "tzCode":"America/Tijuana", },
    { label:"America/Vancouver (GMT-08:00)", "tzCode":"America/Vancouver", },
    { label:"Pacific/Pitcairn (GMT-08:00)", "tzCode":"Pacific/Pitcairn", },
    { label:"America/Boise (GMT-07:00)", "tzCode":"America/Boise", },
    { label:"America/Cambridge_Bay (GMT-07:00)", "tzCode":"America/Cambridge_Bay", },
    { label:"America/Chihuahua (GMT-07:00)", "tzCode":"America/Chihuahua", },
    { label:"America/Creston (GMT-07:00)", "tzCode":"America/Creston", },
    { label:"America/Dawson (GMT-07:00)", "tzCode":"America/Dawson", },
    { label:"America/Dawson_Creek (GMT-07:00)", "tzCode":"America/Dawson_Creek", },
    { label:"America/Denver (GMT-07:00)", "tzCode":"America/Denver", },
    { label:"America/Edmonton (GMT-07:00)", "tzCode":"America/Edmonton", },
    { label:"America/Fort_Nelson (GMT-07:00)", "tzCode":"America/Fort_Nelson", },
    { label:"America/Hermosillo (GMT-07:00)", "tzCode":"America/Hermosillo", },
    { label:"America/Inuvik (GMT-07:00)", "tzCode":"America/Inuvik", },
    { label:"America/Mazatlan (GMT-07:00)", "tzCode":"America/Mazatlan", },
    { label:"America/Ojinaga (GMT-07:00)", "tzCode":"America/Ojinaga", },
    { label:"America/Phoenix (GMT-07:00)", "tzCode":"America/Phoenix", },
    { label:"America/Whitehorse (GMT-07:00)", "tzCode":"America/Whitehorse", },
    { label:"America/Yellowknife (GMT-07:00)", "tzCode":"America/Yellowknife", },
    { label:"America/Bahia_Banderas (GMT-06:00)", "tzCode":"America/Bahia_Banderas", },
    { label:"America/Belize (GMT-06:00)", "tzCode":"America/Belize", },
    { label:"America/Chicago (GMT-06:00)", "tzCode":"America/Chicago", },
    { label:"America/Costa_Rica (GMT-06:00)", "tzCode":"America/Costa_Rica", },
    { label:"America/El_Salvador (GMT-06:00)", "tzCode":"America/El_Salvador", },
    { label:"America/Guatemala (GMT-06:00)", "tzCode":"America/Guatemala", },
    { label:"America/Indiana/Knox (GMT-06:00)", "tzCode":"America/Indiana/Knox", },
    { label:"America/Indiana/Tell_City (GMT-06:00)", "tzCode":"America/Indiana/Tell_City", },
    { label:"America/Managua (GMT-06:00)", "tzCode":"America/Managua", },
    { label:"America/Matamoros (GMT-06:00)", "tzCode":"America/Matamoros", },
    { label:"America/Menominee (GMT-06:00)", "tzCode":"America/Menominee", },
    { label:"America/Merida (GMT-06:00)", "tzCode":"America/Merida", },
    { label:"America/Mexico_City (GMT-06:00)", "tzCode":"America/Mexico_City", },
    { label:"America/Monterrey (GMT-06:00)", "tzCode":"America/Monterrey", },
    { label:"America/North_Dakota/Beulah (GMT-06:00)", "tzCode":"America/North_Dakota/Beulah", },
    { label:"America/North_Dakota/Center (GMT-06:00)", "tzCode":"America/North_Dakota/Center", },
    { label:"America/North_Dakota/New_Salem (GMT-06:00)", "tzCode":"America/North_Dakota/New_Salem", },
    { label:"America/Rainy_River (GMT-06:00)", "tzCode":"America/Rainy_River", },
    { label:"America/Rankin_Inlet (GMT-06:00)", "tzCode":"America/Rankin_Inlet", },
    { label:"America/Regina (GMT-06:00)", "tzCode":"America/Regina", },
    { label:"America/Resolute (GMT-06:00)", "tzCode":"America/Resolute", },
    { label:"America/Swift_Current (GMT-06:00)", "tzCode":"America/Swift_Current", },
    { label:"America/Tegucigalpa (GMT-06:00)", "tzCode":"America/Tegucigalpa", },
    { label:"America/Winnipeg (GMT-06:00)", "tzCode":"America/Winnipeg", },
    { label:"Pacific/Easter (GMT-06:00)", "tzCode":"Pacific/Easter", },
    { label:"Pacific/Galapagos (GMT-06:00)", "tzCode":"Pacific/Galapagos", },
    { label:"America/Atikokan (GMT-05:00)", "tzCode":"America/Atikokan", },
    { label:"America/Bogota (GMT-05:00)", "tzCode":"America/Bogota", },
    { label:"America/Cancun (GMT-05:00)", "tzCode":"America/Cancun", },
    { label:"America/Cayman (GMT-05:00)", "tzCode":"America/Cayman", },
    { label:"America/Detroit (GMT-05:00)", "tzCode":"America/Detroit", },
    { label:"America/Eirunepe (GMT-05:00)", "tzCode":"America/Eirunepe", },
    { label:"America/Grand_Turk (GMT-05:00)", "tzCode":"America/Grand_Turk", },
    { label:"America/Guayaquil (GMT-05:00)", "tzCode":"America/Guayaquil", },
    { label:"America/Havana (GMT-05:00)", "tzCode":"America/Havana", },
    { label:"America/Indiana/Indianapolis (GMT-05:00)", "tzCode":"America/Indiana/Indianapolis", },
    { label:"America/Indiana/Marengo (GMT-05:00)", "tzCode":"America/Indiana/Marengo", },
    { label:"America/Indiana/Petersburg (GMT-05:00)", "tzCode":"America/Indiana/Petersburg", },
    { label:"America/Indiana/Vevay (GMT-05:00)", "tzCode":"America/Indiana/Vevay", },
    { label:"America/Indiana/Vincennes (GMT-05:00)", "tzCode":"America/Indiana/Vincennes", },
    { label:"America/Indiana/Winamac (GMT-05:00)", "tzCode":"America/Indiana/Winamac", },
    { label:"America/Iqaluit (GMT-05:00)", "tzCode":"America/Iqaluit", },
    { label:"America/Jamaica (GMT-05:00)", "tzCode":"America/Jamaica", },
    { label:"America/Kentucky/Louisville (GMT-05:00)", "tzCode":"America/Kentucky/Louisville", },
    { label:"America/Kentucky/Monticello (GMT-05:00)", "tzCode":"America/Kentucky/Monticello", },
    { label:"America/Lima (GMT-05:00)", "tzCode":"America/Lima", },
    { label:"America/Nassau (GMT-05:00)", "tzCode":"America/Nassau", },
    { label:"America/New_York (GMT-05:00)", "tzCode":"America/New_York", },
    { label:"America/Nipigon (GMT-05:00)", "tzCode":"America/Nipigon", },
    { label:"America/Panama (GMT-05:00)", "tzCode":"America/Panama", },
    { label:"America/Pangnirtung (GMT-05:00)", "tzCode":"America/Pangnirtung", },
    { label:"America/Port-au-Prince (GMT-05:00)", "tzCode":"America/Port-au-Prince", },
    { label:"America/Rio_Branco (GMT-05:00)", "tzCode":"America/Rio_Branco", },
    { label:"America/Thunder_Bay (GMT-05:00)", "tzCode":"America/Thunder_Bay", },
    { label:"America/Toronto (GMT-05:00)", "tzCode":"America/Toronto", },
    { label:"America/AnguillaSandy Hill (GMT-04:00)", "tzCode":"America/AnguillaSandy Hill", },
    { label:"America/Antigua (GMT-04:00)", "tzCode":"America/Antigua", },
    { label:"America/Aruba (GMT-04:00)", "tzCode":"America/Aruba", },
    { label:"America/Asuncion (GMT-04:00)", "tzCode":"America/Asuncion", },
    { label:"America/Barbados (GMT-04:00)", "tzCode":"America/Barbados", },
    { label:"America/Blanc-Sablon (GMT-04:00)", "tzCode":"America/Blanc-Sablon", },
    { label:"America/Boa_Vista (GMT-04:00)", "tzCode":"America/Boa_Vista", },
    { label:"America/Campo_Grande (GMT-04:00)", "tzCode":"America/Campo_Grande", },
    { label:"America/Caracas (GMT-04:00)", "tzCode":"America/Caracas", },
    { label:"America/Cuiaba (GMT-04:00)", "tzCode":"America/Cuiaba", },
    { label:"America/Curacao (GMT-04:00)", "tzCode":"America/Curacao", },
    { label:"America/Dominica (GMT-04:00)", "tzCode":"America/Dominica", },
    { label:"America/Glace_Bay (GMT-04:00)", "tzCode":"America/Glace_Bay", },
    { label:"America/Goose_Bay (GMT-04:00)", "tzCode":"America/Goose_Bay", },
    { label:"America/Grenada (GMT-04:00)", "tzCode":"America/Grenada", },
    { label:"America/Guadeloupe (GMT-04:00)", "tzCode":"America/Guadeloupe", },
    { label:"America/Guyana (GMT-04:00)", "tzCode":"America/Guyana", },
    { label:"America/Halifax (GMT-04:00)", "tzCode":"America/Halifax", },
    { label:"America/Kralendijk (GMT-04:00)", "tzCode":"America/Kralendijk", },
    { label:"America/La_Paz (GMT-04:00)", "tzCode":"America/La_Paz", },
    { label:"America/Lower_Princes (GMT-04:00)", "tzCode":"America/Lower_Princes", },
    { label:"America/Manaus (GMT-04:00)", "tzCode":"America/Manaus", },
    { label:"America/Marigot (GMT-04:00)", "tzCode":"America/Marigot", },
    { label:"America/Martinique (GMT-04:00)", "tzCode":"America/Martinique", },
    { label:"America/Moncton (GMT-04:00)", "tzCode":"America/Moncton", },
    { label:"America/Montserrat (GMT-04:00)", "tzCode":"America/Montserrat", },
    { label:"America/Porto_Velho (GMT-04:00)", "tzCode":"America/Porto_Velho", },
    { label:"America/Port_of_Spain (GMT-04:00)", "tzCode":"America/Port_of_Spain", },
    { label:"America/Puerto_Rico (GMT-04:00)", "tzCode":"America/Puerto_Rico", },
    { label:"America/Santiago (GMT-04:00)", "tzCode":"America/Santiago", },
    { label:"America/Santo_Domingo (GMT-04:00)", "tzCode":"America/Santo_Domingo", },
    { label:"America/St_Barthelemy (GMT-04:00)", "tzCode":"America/St_Barthelemy", },
    { label:"America/St_Kitts (GMT-04:00)", "tzCode":"America/St_Kitts", },
    { label:"America/St_Lucia (GMT-04:00)", "tzCode":"America/St_Lucia", },
    { label:"America/St_Thomas (GMT-04:00)", "tzCode":"America/St_Thomas", },
    { label:"America/St_Vincent (GMT-04:00)", "tzCode":"America/St_Vincent", },
    { label:"America/Thule (GMT-04:00)", "tzCode":"America/Thule", },
    { label:"America/Tortola (GMT-04:00)", "tzCode":"America/Tortola", },
    { label:"Atlantic/Bermuda (GMT-04:00)", "tzCode":"Atlantic/Bermuda", },
    { label:"America/St_Johns (GMT-03:30)", "tzCode":"America/St_Johns", },
    { label:"America/Araguaina (GMT-03:00)", "tzCode":"America/Araguaina", },
    { label:"America/Argentina/Buenos_Aires (GMT-03:00)", "tzCode":"America/Argentina/Buenos_Aires", },
    { label:"America/Argentina/Catamarca (GMT-03:00)", "tzCode":"America/Argentina/Catamarca", },
    { label:"America/Argentina/Cordoba (GMT-03:00)", "tzCode":"America/Argentina/Cordoba", },
    { label:"America/Argentina/Jujuy (GMT-03:00)", "tzCode":"America/Argentina/Jujuy", },
    { label:"America/Argentina/La_Rioja (GMT-03:00)", "tzCode":"America/Argentina/La_Rioja", },
    { label:"America/Argentina/Mendoza (GMT-03:00)", "tzCode":"America/Argentina/Mendoza", },
    { label:"America/Argentina/Rio_Gallegos (GMT-03:00)", "tzCode":"America/Argentina/Rio_Gallegos", },
    { label:"America/Argentina/Salta (GMT-03:00)", "tzCode":"America/Argentina/Salta", },
    { label:"America/Argentina/San_Juan (GMT-03:00)", "tzCode":"America/Argentina/San_Juan", },
    { label:"America/Argentina/San_Luis (GMT-03:00)", "tzCode":"America/Argentina/San_Luis", },
    { label:"America/Argentina/Tucuman (GMT-03:00)", "tzCode":"America/Argentina/Tucuman", },
    { label:"America/Argentina/Ushuaia (GMT-03:00)", "tzCode":"America/Argentina/Ushuaia", },
    { label:"America/Bahia (GMT-03:00)", "tzCode":"America/Bahia", },
    { label:"America/Belem (GMT-03:00)", "tzCode":"America/Belem", },
    { label:"America/Cayenne (GMT-03:00)", "tzCode":"America/Cayenne", },
    { label:"America/Fortaleza (GMT-03:00)", "tzCode":"America/Fortaleza", },
    { label:"America/Godthab (GMT-03:00)", "tzCode":"America/Godthab", },
    { label:"America/Maceio (GMT-03:00)", "tzCode":"America/Maceio", },
    { label:"America/Miquelon (GMT-03:00)", "tzCode":"America/Miquelon", },
    { label:"America/Montevideo (GMT-03:00)", "tzCode":"America/Montevideo", },
    { label:"America/Paramaribo (GMT-03:00)", "tzCode":"America/Paramaribo", },
    { label:"America/Punta_Arenas (GMT-03:00)", "tzCode":"America/Punta_Arenas", },
    { label:"America/Recife (GMT-03:00)", "tzCode":"America/Recife", },
    { label:"America/Santarem (GMT-03:00)", "tzCode":"America/Santarem", },
    { label:"America/Sao_Paulo (GMT-03:00)", "tzCode":"America/Sao_Paulo", },
    { label:"Antarctica/Palmer (GMT-03:00)", "tzCode":"Antarctica/Palmer", },
    { label:"Antarctica/Rothera (GMT-03:00)", "tzCode":"Antarctica/Rothera", },
    { label:"Atlantic/Stanley (GMT-03:00)", "tzCode":"Atlantic/Stanley", },
    { label:"America/Noronha (GMT-02:00)", "tzCode":"America/Noronha", },
    { label:"Atlantic/South_Georgia (GMT-02:00)", "tzCode":"Atlantic/South_Georgia", },
    { label:"America/Scoresbysund (GMT-01:00)", "tzCode":"America/Scoresbysund", },
    { label:"Atlantic/Azores (GMT-01:00)", "tzCode":"Atlantic/Azores", },
    { label:"Atlantic/Cape_Verde (GMT-01:00)", "tzCode":"Atlantic/Cape_Verde", },
    { label:"Africa/Abidjan (GMT+00:00)", "tzCode":"Africa/Abidjan", },
    { label:"Africa/Accra (GMT+00:00)", "tzCode":"Africa/Accra", },
    { label:"Africa/Bamako (GMT+00:00)", "tzCode":"Africa/Bamako", },
    { label:"Africa/Banjul (GMT+00:00)", "tzCode":"Africa/Banjul", },
    { label:"Africa/Bissau (GMT+00:00)", "tzCode":"Africa/Bissau", },
    { label:"Africa/Casablanca (GMT+00:00)", "tzCode":"Africa/Casablanca", },
    { label:"Africa/Conakry (GMT+00:00)", "tzCode":"Africa/Conakry", },
    { label:"Africa/Dakar (GMT+00:00)", "tzCode":"Africa/Dakar", },
    { label:"Africa/El_Aaiun (GMT+00:00)", "tzCode":"Africa/El_Aaiun", },
    { label:"Africa/Freetown (GMT+00:00)", "tzCode":"Africa/Freetown", },
    { label:"Africa/Lome (GMT+00:00)", "tzCode":"Africa/Lome", },
    { label:"Africa/Monrovia (GMT+00:00)", "tzCode":"Africa/Monrovia", },
    { label:"Africa/Nouakchott (GMT+00:00)", "tzCode":"Africa/Nouakchott", },
    { label:"Africa/Ouagadougou (GMT+00:00)", "tzCode":"Africa/Ouagadougou", },
    { label:"Africa/Sao_Tome (GMT+00:00)", "tzCode":"Africa/Sao_Tome", },
    { label:"America/Danmarkshavn (GMT+00:00)", "tzCode":"America/Danmarkshavn", },
    { label:"Antarctica/Troll (GMT+00:00)", "tzCode":"Antarctica/Troll", },
    { label:"Atlantic/Canary (GMT+00:00)", "tzCode":"Atlantic/Canary", },
    { label:"Atlantic/Faroe (GMT+00:00)", "tzCode":"Atlantic/Faroe", },
    { label:"Atlantic/Madeira (GMT+00:00)", "tzCode":"Atlantic/Madeira", },
    { label:"Atlantic/Reykjavik (GMT+00:00)", "tzCode":"Atlantic/Reykjavik", },
    { label:"Atlantic/St_Helena (GMT+00:00)", "tzCode":"Atlantic/St_Helena", },
    { label:"Europe/Dublin (GMT+00:00)", "tzCode":"Europe/Dublin", },
    { label:"Europe/Guernsey (GMT+00:00)", "tzCode":"Europe/Guernsey", },
    { label:"Europe/Isle_of_Man (GMT+00:00)", "tzCode":"Europe/Isle_of_Man", },
    { label:"Europe/Jersey (GMT+00:00)", "tzCode":"Europe/Jersey", },
    { label:"Europe/Lisbon (GMT+00:00)", "tzCode":"Europe/Lisbon", },
    { label:"Europe/London (GMT+00:00)", "tzCode":"Europe/London", },
    { label:"Africa/Algiers (GMT+01:00)", "tzCode":"Africa/Algiers", },
    { label:"Africa/Bangui (GMT+01:00)", "tzCode":"Africa/Bangui", },
    { label:"Africa/Brazzaville (GMT+01:00)", "tzCode":"Africa/Brazzaville", },
    { label:"Africa/Ceuta (GMT+01:00)", "tzCode":"Africa/Ceuta", },
    { label:"Africa/Douala (GMT+01:00)", "tzCode":"Africa/Douala", },
    { label:"Africa/Kinshasa (GMT+01:00)", "tzCode":"Africa/Kinshasa", },
    { label:"Africa/Lagos (GMT+01:00)", "tzCode":"Africa/Lagos", },
    { label:"Africa/Libreville (GMT+01:00)", "tzCode":"Africa/Libreville", },
    { label:"Africa/Luanda (GMT+01:00)", "tzCode":"Africa/Luanda", },
    { label:"Africa/Malabo (GMT+01:00)", "tzCode":"Africa/Malabo", },
    { label:"Africa/Ndjamena (GMT+01:00)", "tzCode":"Africa/Ndjamena", },
    { label:"Africa/Niamey (GMT+01:00)", "tzCode":"Africa/Niamey", },
    { label:"Africa/Porto-Novo (GMT+01:00)", "tzCode":"Africa/Porto-Novo", },
    { label:"Africa/Tunis (GMT+01:00)", "tzCode":"Africa/Tunis", },
    { label:"Africa/Windhoek (GMT+01:00)", "tzCode":"Africa/Windhoek", },
    { label:"Arctic/Longyearbyen (GMT+01:00)", "tzCode":"Arctic/Longyearbyen", },
    { label:"Europe/Amsterdam (GMT+01:00)", "tzCode":"Europe/Amsterdam", },
    { label:"Europe/Andorra (GMT+01:00)", "tzCode":"Europe/Andorra", },
    { label:"Europe/Belgrade (GMT+01:00)", "tzCode":"Europe/Belgrade", },
    { label:"Europe/Berlin (GMT+01:00)", "tzCode":"Europe/Berlin", },
    { label:"Europe/Bratislava (GMT+01:00)", "tzCode":"Europe/Bratislava", },
    { label:"Europe/Brussels (GMT+01:00)", "tzCode":"Europe/Brussels", },
    { label:"Europe/Budapest (GMT+01:00)", "tzCode":"Europe/Budapest", },
    { label:"Europe/Copenhagen (GMT+01:00)", "tzCode":"Europe/Copenhagen", },
    { label:"Europe/Gibraltar (GMT+01:00)", "tzCode":"Europe/Gibraltar", },
    { label:"Europe/Ljubljana (GMT+01:00)", "tzCode":"Europe/Ljubljana", },
    { label:"Europe/Luxembourg (GMT+01:00)", "tzCode":"Europe/Luxembourg", },
    { label:"Europe/Madrid (GMT+01:00)", "tzCode":"Europe/Madrid", },
    { label:"Europe/Malta (GMT+01:00)", "tzCode":"Europe/Malta", },
    { label:"Europe/Monaco (GMT+01:00)", "tzCode":"Europe/Monaco", },
    { label:"Europe/Oslo (GMT+01:00)", "tzCode":"Europe/Oslo", },
    { label:"Europe/Paris (GMT+01:00)", "tzCode":"Europe/Paris", },
    { label:"Europe/Podgorica (GMT+01:00)", "tzCode":"Europe/Podgorica", },
    { label:"Europe/Prague (GMT+01:00)", "tzCode":"Europe/Prague", },
    { label:"Europe/Rome (GMT+01:00)", "tzCode":"Europe/Rome", },
    { label:"Europe/San_Marino (GMT+01:00)", "tzCode":"Europe/San_Marino", },
    { label:"Europe/Sarajevo (GMT+01:00)", "tzCode":"Europe/Sarajevo", },
    { label:"Europe/Skopje (GMT+01:00)", "tzCode":"Europe/Skopje", },
    { label:"Europe/Stockholm (GMT+01:00)", "tzCode":"Europe/Stockholm", },
    { label:"Europe/Tirane (GMT+01:00)", "tzCode":"Europe/Tirane", },
    { label:"Europe/Vaduz (GMT+01:00)", "tzCode":"Europe/Vaduz", },
    { label:"Europe/Vatican (GMT+01:00)", "tzCode":"Europe/Vatican", },
    { label:"Europe/Vienna (GMT+01:00)", "tzCode":"Europe/Vienna", },
    { label:"Europe/Warsaw (GMT+01:00)", "tzCode":"Europe/Warsaw", },
    { label:"Europe/Zagreb (GMT+01:00)", "tzCode":"Europe/Zagreb", },
    { label:"Europe/Zurich (GMT+01:00)", "tzCode":"Europe/Zurich", },
    { label:"Africa/Blantyre (GMT+02:00)", "tzCode":"Africa/Blantyre", },
    { label:"Africa/Bujumbura (GMT+02:00)", "tzCode":"Africa/Bujumbura", },
    { label:"Africa/Cairo (GMT+02:00)", "tzCode":"Africa/Cairo", },
    { label:"Africa/Gaborone (GMT+02:00)", "tzCode":"Africa/Gaborone", },
    { label:"Africa/Harare (GMT+02:00)", "tzCode":"Africa/Harare", },
    { label:"Africa/Johannesburg (GMT+02:00)", "tzCode":"Africa/Johannesburg", },
    { label:"Africa/Juba (GMT+02:00)", "tzCode":"Africa/Juba", },
    { label:"Africa/Khartoum (GMT+02:00)", "tzCode":"Africa/Khartoum", },
    { label:"Africa/Kigali (GMT+02:00)", "tzCode":"Africa/Kigali", },
    { label:"Africa/Lubumbashi (GMT+02:00)", "tzCode":"Africa/Lubumbashi", },
    { label:"Africa/Lusaka (GMT+02:00)", "tzCode":"Africa/Lusaka", },
    { label:"Africa/Maputo (GMT+02:00)", "tzCode":"Africa/Maputo", },
    { label:"Africa/Maseru (GMT+02:00)", "tzCode":"Africa/Maseru", },
    { label:"Africa/Mbabane (GMT+02:00)", "tzCode":"Africa/Mbabane", },
    { label:"Africa/Tripoli (GMT+02:00)", "tzCode":"Africa/Tripoli", },
    { label:"Asia/Amman (GMT+02:00)", "tzCode":"Asia/Amman", },
    { label:"Asia/Beirut (GMT+02:00)", "tzCode":"Asia/Beirut", },
    { label:"Asia/Damascus (GMT+02:00)", "tzCode":"Asia/Damascus", },
    { label:"Asia/Famagusta (GMT+02:00)", "tzCode":"Asia/Famagusta", },
    { label:"Asia/Gaza (GMT+02:00)", "tzCode":"Asia/Gaza", },
    { label:"Asia/Hebron (GMT+02:00)", "tzCode":"Asia/Hebron", },
    { label:"Asia/Jerusalem (GMT+02:00)", "tzCode":"Asia/Jerusalem", },
    { label:"Asia/Nicosia (GMT+02:00)", "tzCode":"Asia/Nicosia", },
    { label:"Europe/Athens (GMT+02:00)", "tzCode":"Europe/Athens", },
    { label:"Europe/Bucharest (GMT+02:00)", "tzCode":"Europe/Bucharest", },
    { label:"Europe/Chisinau (GMT+02:00)", "tzCode":"Europe/Chisinau", },
    { label:"Europe/Helsinki (GMT+02:00)", "tzCode":"Europe/Helsinki", },
    { label:"Europe/Kaliningrad (GMT+02:00)", "tzCode":"Europe/Kaliningrad", },
    { label:"Europe/Kyiv (GMT+02:00)", "tzCode":"Europe/Kyiv", },
    { label:"Europe/Mariehamn (GMT+02:00)", "tzCode":"Europe/Mariehamn", },
    { label:"Europe/Riga (GMT+02:00)", "tzCode":"Europe/Riga", },
    { label:"Europe/Sofia (GMT+02:00)", "tzCode":"Europe/Sofia", },
    { label:"Europe/Tallinn (GMT+02:00)", "tzCode":"Europe/Tallinn", },
    { label:"Europe/Uzhgorod (GMT+02:00)", "tzCode":"Europe/Uzhgorod", },
    { label:"Europe/Vilnius (GMT+02:00)", "tzCode":"Europe/Vilnius", },
    { label:"Europe/Zaporozhye (GMT+02:00)", "tzCode":"Europe/Zaporozhye", },
    { label:"Africa/Addis_Ababa (GMT+03:00)", "tzCode":"Africa/Addis_Ababa", },
    { label:"Africa/Asmara (GMT+03:00)", "tzCode":"Africa/Asmara", },
    { label:"Africa/Dar_es_Salaam (GMT+03:00)", "tzCode":"Africa/Dar_es_Salaam", },
    { label:"Africa/Djibouti (GMT+03:00)", "tzCode":"Africa/Djibouti", },
    { label:"Africa/Kampala (GMT+03:00)", "tzCode":"Africa/Kampala", },
    { label:"Africa/Mogadishu (GMT+03:00)", "tzCode":"Africa/Mogadishu", },
    { label:"Africa/Nairobi (GMT+03:00)", "tzCode":"Africa/Nairobi", },
    { label:"Antarctica/Syowa (GMT+03:00)", "tzCode":"Antarctica/Syowa", },
    { label:"Asia/Aden (GMT+03:00)", "tzCode":"Asia/Aden", },
    { label:"Asia/Baghdad (GMT+03:00)", "tzCode":"Asia/Baghdad", },
    { label:"Asia/Bahrain (GMT+03:00)", "tzCode":"Asia/Bahrain", },
    { label:"Asia/Kuwait (GMT+03:00)", "tzCode":"Asia/Kuwait", },
    { label:"Asia/Qatar (GMT+03:00)", "tzCode":"Asia/Qatar", },
    { label:"Asia/Riyadh (GMT+03:00)", "tzCode":"Asia/Riyadh", },
    { label:"Europe/Istanbul (GMT+03:00)", "tzCode":"Europe/Istanbul", },
    { label:"Europe/Kirov (GMT+03:00)", "tzCode":"Europe/Kirov", },
    { label:"Europe/Minsk (GMT+03:00)", "tzCode":"Europe/Minsk", },
    { label:"Europe/Moscow (GMT+03:00)", "tzCode":"Europe/Moscow", },
    { label:"Europe/Simferopol (GMT+03:00)", "tzCode":"Europe/Simferopol", },
    { label:"Europe/Volgograd (GMT+03:00)", "tzCode":"Europe/Volgograd", },
    { label:"Indian/Antananarivo (GMT+03:00)", "tzCode":"Indian/Antananarivo", },
    { label:"Indian/Comoro (GMT+03:00)", "tzCode":"Indian/Comoro", },
    { label:"Indian/Mayotte (GMT+03:00)", "tzCode":"Indian/Mayotte", },
    { label:"Asia/Tehran (GMT+03:30)", "tzCode":"Asia/Tehran", },
    { label:"Asia/Baku (GMT+04:00)", "tzCode":"Asia/Baku", },
    { label:"Asia/Dubai (GMT+04:00)", "tzCode":"Asia/Dubai", },
    { label:"Asia/Muscat (GMT+04:00)", "tzCode":"Asia/Muscat", },
    { label:"Asia/Tbilisi (GMT+04:00)", "tzCode":"Asia/Tbilisi", },
    { label:"Asia/Yerevan (GMT+04:00)", "tzCode":"Asia/Yerevan", },
    { label:"Europe/Astrakhan (GMT+04:00)", "tzCode":"Europe/Astrakhan", },
    { label:"Europe/Samara (GMT+04:00)", "tzCode":"Europe/Samara", },
    { label:"Europe/Saratov (GMT+04:00)", "tzCode":"Europe/Saratov", },
    { label:"Europe/Ulyanovsk (GMT+04:00)", "tzCode":"Europe/Ulyanovsk", },
    { label:"Indian/Mahe (GMT+04:00)", "tzCode":"Indian/Mahe", },
    { label:"Indian/Mauritius (GMT+04:00)", "tzCode":"Indian/Mauritius", },
    { label:"Indian/Reunion (GMT+04:00)", "tzCode":"Indian/Reunion", },
    { label:"Asia/Kabul (GMT+04:30)", "tzCode":"Asia/Kabul", },
    { label:"Antarctica/Mawson (GMT+05:00)", "tzCode":"Antarctica/Mawson", },
    { label:"Asia/Aqtau (GMT+05:00)", "tzCode":"Asia/Aqtau", },
    { label:"Asia/Aqtobe (GMT+05:00)", "tzCode":"Asia/Aqtobe", },
    { label:"Asia/Ashgabat (GMT+05:00)", "tzCode":"Asia/Ashgabat", },
    { label:"Asia/Atyrau (GMT+05:00)", "tzCode":"Asia/Atyrau", },
    { label:"Asia/Dushanbe (GMT+05:00)", "tzCode":"Asia/Dushanbe", },
    { label:"Asia/Karachi (GMT+05:00)", "tzCode":"Asia/Karachi", },
    { label:"Asia/Oral (GMT+05:00)", "tzCode":"Asia/Oral", },
    { label:"Asia/Qyzylorda (GMT+05:00)", "tzCode":"Asia/Qyzylorda", },
    { label:"Asia/Samarkand (GMT+05:00)", "tzCode":"Asia/Samarkand", },
    { label:"Asia/Tashkent (GMT+05:00)", "tzCode":"Asia/Tashkent", },
    { label:"Asia/Yekaterinburg (GMT+05:00)", "tzCode":"Asia/Yekaterinburg", },
    { label:"Indian/Kerguelen (GMT+05:00)", "tzCode":"Indian/Kerguelen", },
    { label:"Indian/Maldives (GMT+05:00)", "tzCode":"Indian/Maldives", },
    { label:"Asia/Colombo (GMT+05:30)", "tzCode":"Asia/Colombo", },
    { label:"Asia/Kolkata (GMT+05:30)", "tzCode":"Asia/Kolkata", },
    { label:"Asia/Kathmandu (GMT+05:45)", "tzCode":"Asia/Kathmandu", },
    { label:"Antarctica/Vostok (GMT+06:00)", "tzCode":"Antarctica/Vostok", },
    { label:"Asia/Almaty (GMT+06:00)", "tzCode":"Asia/Almaty", },
    { label:"Asia/Bishkek (GMT+06:00)", "tzCode":"Asia/Bishkek", },
    { label:"Asia/Dhaka (GMT+06:00)", "tzCode":"Asia/Dhaka", },
    { label:"Asia/Omsk (GMT+06:00)", "tzCode":"Asia/Omsk", },
    { label:"Asia/Qostanay (GMT+06:00)", "tzCode":"Asia/Qostanay", },
    { label:"Asia/Thimphu (GMT+06:00)", "tzCode":"Asia/Thimphu", },
    { label:"Asia/Urumqi (GMT+06:00)", "tzCode":"Asia/Urumqi", },
    { label:"Indian/Chagos (GMT+06:00)", "tzCode":"Indian/Chagos", },
    { label:"Asia/Yangon (GMT+06:30)", "tzCode":"Asia/Yangon", },
    { label:"Indian/Cocos (GMT+06:30)", "tzCode":"Indian/Cocos", },
    { label:"Antarctica/Davis (GMT+07:00)", "tzCode":"Antarctica/Davis", },
    { label:"Asia/Bangkok (GMT+07:00)", "tzCode":"Asia/Bangkok", },
    { label:"Asia/Barnaul (GMT+07:00)", "tzCode":"Asia/Barnaul", },
    { label:"Asia/Hovd (GMT+07:00)", "tzCode":"Asia/Hovd", },
    { label:"Asia/Ho_Chi_Minh (GMT+07:00)", "tzCode":"Asia/Ho_Chi_Minh", },
    { label:"Asia/Jakarta (GMT+07:00)", "tzCode":"Asia/Jakarta", },
    { label:"Asia/Krasnoyarsk (GMT+07:00)", "tzCode":"Asia/Krasnoyarsk", },
    { label:"Asia/Novokuznetsk (GMT+07:00)", "tzCode":"Asia/Novokuznetsk", },
    { label:"Asia/Novosibirsk (GMT+07:00)", "tzCode":"Asia/Novosibirsk", },
    { label:"Asia/Phnom_Penh (GMT+07:00)", "tzCode":"Asia/Phnom_Penh", },
    { label:"Asia/Pontianak (GMT+07:00)", "tzCode":"Asia/Pontianak", },
    { label:"Asia/Tomsk (GMT+07:00)", "tzCode":"Asia/Tomsk", },
    { label:"Asia/Vientiane (GMT+07:00)", "tzCode":"Asia/Vientiane", },
    { label:"Indian/Christmas (GMT+07:00)", "tzCode":"Indian/Christmas", },
    { label:"Asia/Brunei (GMT+08:00)", "tzCode":"Asia/Brunei", },
    { label:"Asia/Choibalsan (GMT+08:00)", "tzCode":"Asia/Choibalsan", },
    { label:"Asia/Hong_Kong (GMT+08:00)", "tzCode":"Asia/Hong_Kong", },
    { label:"Asia/Irkutsk (GMT+08:00)", "tzCode":"Asia/Irkutsk", },
    { label:"Asia/Kuala_Lumpur (GMT+08:00)", "tzCode":"Asia/Kuala_Lumpur", },
    { label:"Asia/Kuching (GMT+08:00)", "tzCode":"Asia/Kuching", },
    { label:"Asia/Macau (GMT+08:00)", "tzCode":"Asia/Macau", },
    { label:"Asia/Makassar (GMT+08:00)", "tzCode":"Asia/Makassar", },
    { label:"Asia/Manila (GMT+08:00)", "tzCode":"Asia/Manila", },
    { label:"Asia/Shanghai (GMT+08:00)", "tzCode":"Asia/Shanghai", },
    { label:"Asia/Singapore (GMT+08:00)", "tzCode":"Asia/Singapore", },
    { label:"Asia/Taipei (GMT+08:00)", "tzCode":"Asia/Taipei", },
    { label:"Asia/Ulaanbaatar (GMT+08:00)", "tzCode":"Asia/Ulaanbaatar", },
    { label:"Australia/Perth (GMT+08:00)", "tzCode":"Australia/Perth", },
    { label:"Australia/Eucla (GMT+08:45)", "tzCode":"Australia/Eucla", },
    { label:"Asia/Chita (GMT+09:00)", "tzCode":"Asia/Chita", },
    { label:"Asia/Dili (GMT+09:00)", "tzCode":"Asia/Dili", },
    { label:"Asia/Jayapura (GMT+09:00)", "tzCode":"Asia/Jayapura", },
    { label:"Asia/Khandyga (GMT+09:00)", "tzCode":"Asia/Khandyga", },
    { label:"Asia/Pyongyang (GMT+09:00)", "tzCode":"Asia/Pyongyang", },
    { label:"Asia/Seoul (GMT+09:00)", "tzCode":"Asia/Seoul", },
    { label:"Asia/Tokyo (GMT+09:00)", "tzCode":"Asia/Tokyo", },
    { label:"Asia/Yakutsk (GMT+09:00)", "tzCode":"Asia/Yakutsk", },
    { label:"Pacific/Palau (GMT+09:00)", "tzCode":"Pacific/Palau", },
    { label:"Australia/Adelaide (GMT+09:30)", "tzCode":"Australia/Adelaide", },
    { label:"Australia/Broken_Hill (GMT+09:30)", "tzCode":"Australia/Broken_Hill", },
    { label:"Australia/Darwin (GMT+09:30)", "tzCode":"Australia/Darwin", },
    { label:"Antarctica/DumontDUrville (GMT+10:00)", "tzCode":"Antarctica/DumontDUrville", },
    { label:"Antarctica/Macquarie (GMT+10:00)", "tzCode":"Antarctica/Macquarie", },
    { label:"Asia/Ust-Nera (GMT+10:00)", "tzCode":"Asia/Ust-Nera", },
    { label:"Asia/Vladivostok (GMT+10:00)", "tzCode":"Asia/Vladivostok", },
    { label:"Australia/Brisbane (GMT+10:00)", "tzCode":"Australia/Brisbane", },
    { label:"Australia/Currie (GMT+10:00)", "tzCode":"Australia/Currie", },
    { label:"Australia/Hobart (GMT+10:00)", "tzCode":"Australia/Hobart", },
    { label:"Australia/Lindeman (GMT+10:00)", "tzCode":"Australia/Lindeman", },
    { label:"Australia/Melbourne (GMT+10:00)", "tzCode":"Australia/Melbourne", },
    { label:"Australia/Sydney (GMT+10:00)", "tzCode":"Australia/Sydney", },
    { label:"Pacific/Chuuk (GMT+10:00)", "tzCode":"Pacific/Chuuk", },
    { label:"Pacific/GuamVillage (GMT+10:00)", "tzCode":"Pacific/GuamVillage", },
    { label:"Pacific/Port_Moresby (GMT+10:00)", "tzCode":"Pacific/Port_Moresby", },
    { label:"Pacific/Saipan (GMT+10:00)", "tzCode":"Pacific/Saipan", },
    { label:"Australia/Lord_Howe (GMT+10:30)", "tzCode":"Australia/Lord_Howe", },
    { label:"Antarctica/Casey (GMT+11:00)", "tzCode":"Antarctica/Casey", },
    { label:"Asia/Magadan (GMT+11:00)", "tzCode":"Asia/Magadan", },
    { label:"Asia/Sakhalin (GMT+11:00)", "tzCode":"Asia/Sakhalin", },
    { label:"Asia/Srednekolymsk (GMT+11:00)", "tzCode":"Asia/Srednekolymsk", },
    { label:"Pacific/Bougainville (GMT+11:00)", "tzCode":"Pacific/Bougainville", },
    { label:"Pacific/Efate (GMT+11:00)", "tzCode":"Pacific/Efate", },
    { label:"Pacific/Guadalcanal (GMT+11:00)", "tzCode":"Pacific/Guadalcanal", },
    { label:"Pacific/Kosrae (GMT+11:00)", "tzCode":"Pacific/Kosrae", },
    { label:"Pacific/Norfolk (GMT+11:00)", "tzCode":"Pacific/Norfolk", },
    { label:"Pacific/Noumea (GMT+11:00)", "tzCode":"Pacific/Noumea", },
    { label:"Pacific/Pohnpei (GMT+11:00)", "tzCode":"Pacific/Pohnpei", },
    { label:"Antarctica/McMurdo (GMT+12:00)", "tzCode":"Antarctica/McMurdo", },
    { label:"Asia/Anadyr (GMT+12:00)", "tzCode":"Asia/Anadyr", },
    { label:"Asia/Kamchatka (GMT+12:00)", "tzCode":"Asia/Kamchatka", },
    { label:"Pacific/Auckland (GMT+12:00)", "tzCode":"Pacific/Auckland", },
    { label:"Pacific/Fiji (GMT+12:00)", "tzCode":"Pacific/Fiji", },
    { label:"Pacific/Funafuti (GMT+12:00)", "tzCode":"Pacific/Funafuti", },
    { label:"Pacific/Kwajalein (GMT+12:00)", "tzCode":"Pacific/Kwajalein", },
    { label:"Pacific/Majuro (GMT+12:00)", "tzCode":"Pacific/Majuro", },
    { label:"Pacific/Nauru (GMT+12:00)", "tzCode":"Pacific/Nauru", },
    { label:"Pacific/Tarawa (GMT+12:00)", "tzCode":"Pacific/Tarawa", },
    { label:"Pacific/Wake (GMT+12:00)", "tzCode":"Pacific/Wake", },
    { label:"Pacific/Wallis (GMT+12:00)", "tzCode":"Pacific/Wallis", },
    { label:"Pacific/Chatham (GMT+12:45)", "tzCode":"Pacific/Chatham", },
    { label:"Pacific/Apia (GMT+13:00)", "tzCode":"Pacific/Apia", },
    { label:"Pacific/Enderbury (GMT+13:00)", "tzCode":"Pacific/Enderbury", },
    { label:"Pacific/Fakaofo (GMT+13:00)", "tzCode":"Pacific/Fakaofo", },
    { label:"Pacific/Tongatapu (GMT+13:00)", "tzCode":"Pacific/Tongatapu", },
    { label:"Pacific/Kiritimati (GMT+14:00)", "tzCode":"Pacific/Kiritimati", }
]

export default {
    name: 'TablerTimeZone',
    components: {
        TablerEnum
    },
    props: {
        modelValue: {
            type: String,
            required: true
        },
        autofocus: {
            type: Boolean,
            default: false
        },
        description: {
            type: String,
            default: ''
        },
        required: {
            type: Boolean
        },
        disabled: {
            type: Boolean,
            default: false
        },
        label: {
            type: String,
            default: 'Default Timezone'
        },
    },
    emits: [
        'update:modelValue'
    ],
    data: function() {
        const map = new Map();
        const inverse = new Map();

        map.set('No TimeZone', { tzCode: '' });
        for (const tz of tzs) {
            map.set(tz.label, tz);
            inverse.set(tz.tzCode, tz.label);
        }

        return {
            map,
            inverse,
            internal: this.modelValue,
            timezones: ['No TimeZone'].concat(tzs.map((tz) => tz.label))
        }
    }
}
</script>
